In [1]:
import warnings
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")
import requests
from bs4 import BeautifulSoup
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, ElementClickInterceptedException

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver=webdriver.Edge(r"C:/Users/DELL/Downloads/edgedriver_win64/msedgedriver.exe")
driver.get(url)
driver.maximize_window()
driver.find_element_by_xpath("//b").click()
records = []
for row in driver.find_elements_by_xpath("(//table[@class='wikitable sortable jquery-tablesorter'])[1]//tr")[1:-1]:
    temp = ''
    for element in row.find_elements_by_xpath(".//td"):        
        temp += element.text + '|'
    records.append(temp.split('|')[:-2])

df = pd.DataFrame(records, columns=['Rank', 'Video_Name', 'Artist_Name', 'Views_in_Billions', 'Upload_Date'])

arranged_cols = ['Rank', 'Video_Name', 'Artist_Name', 'Upload_Date', 'Views_in_Billions']

df.Video_Name = df.Video_Name.apply(lambda x:x[:-4].strip('"'))
df = df[arranged_cols]
df

Legality Response number from our URL is: <Response [200]>

,Rank,Video_Name,Artist_Name,Upload_Date,Views_in_Billions
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.00
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.70
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.10
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.58
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.38
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.86
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.55
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.48
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.42
9,10.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.41
10,11.,Gangnam Style,Psy,"July 15, 2012",4.31
11,12.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.80
12,13.,Sugar,Maroon 5,"January 14, 2015",3.62
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.50
14,15.,Roar,Katy Perry,"September 5, 2013",3.50
15,16.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.50
16,17.,Counting Stars,OneRepublic,"May 31, 2013",3.48
17,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.39
18,19.,Girls Like You,Maroon 5,"May 31, 2018",3.21
19,20.,Faded,Alan Walker,"December 3, 2015",3.21
20,21.,Dark Horse,Katy Perry,"February 20, 2014",3.21
21,22.,Axel F,Crazy Frog,"June 16, 2009",3.17
22,23.,Let Her Go,Passenger,"July 25, 2012",3.15
23,24.,Bailando,Enrique Iglesias,"April 11, 2014",3.15
24,25.,Lean On,Major Lazer,"March 22, 2015",3.15
25,26.,Shake It Off,Taylor Swift,"August 18, 2014",3.13
26,27.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.07
27,28.,Perfect,Ed Sheeran,"November 9, 2017",3.06
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.03
29,30.,Mi Gente,J Balvin,"June 29, 2017",3.03

In [3]:
url = "https://www.bcci.tv/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver=webdriver.Edge(r"C:/Users/DELL/Downloads/edgedriver_win64/msedgedriver.exe")
driver.get(url)
driver.maximize_window()

#clickin on International tab
driver.find_element_by_xpath("//li[@class='nav-item ml-0']").click()

'''#clicking on Fixtures
driver.find_element_by_xpath("//a[@class='nav-link active']").click()'''

# Empty lists
match_title=[]
series=[]
place=[]
date=[]
matchtime=[]
date=[]
time=[]
for i in driver.find_elements_by_xpath("//span[@class='ng-binding']"):
    match_title.append(i.text)
    
'''for i in driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope]"):
    series.append(i.text.strip())
'''
for i in driver.find_elements_by_xpath("//div[@class='fixture__description u-unskewed-text']/p/span"):
    place.append(i.text)
    
for i in driver.find_elements_by_xpath("//div[@class='match-card-left match-schedule']"):
    date.append(i.text)
for i in driver.find_elements_by_xpath("//div[@class='match-card-right match-schedule']"):
    date.append(i.text)


# Creating data frame
matches_data=pd.DataFrame({'Match Title': match_title,
                          "Series": series,
                          "Place": place,
                          "Date": date,
                          "Time": matchtime})
matches_data

Legality Response number from our URL is: <Response [200]>

Empty DataFrame
Columns: [Match Title, Series, Place, Date, Time]
Index: []

In [4]:
url = "https://www.guru99.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver=webdriver.Edge(r"C:/Users/DELL/Downloads/edgedriver_win64/msedgedriver.exe")
driver.get(url)
driver.maximize_window()

error = driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a').get_attribute('href')
driver.get(error)

exception = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a').get_attribute('href')
driver.get(exception)

Data = []
table = driver.find_elements_by_xpath("//table[@class='table table-striped']//td")
for i in table:
    try:
        Data.append(i.text)
    except NoSuchElementException:
        Data.append('-')

Name = []
for i in range(2,len(Data),2):
    Name.append(Data[i])

Description = []
for i in range(3,len(Data),2):
    Description.append(Data[i])

df=pd.DataFrame({"Exception name": Name, "Exception description": Description})
df

Legality Response number from our URL is: <Response [403]>

,Exception name,Exception description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [5]:
url = "https://statisticstimes.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver=webdriver.Edge(r"C:/Users/DELL/Downloads/edgedriver_win64/msedgedriver.exe")
driver.get(url)
driver.maximize_window()

link1=driver.find_element_by_xpath("//div[@class='dropdown-content']/a[3]").get_attribute("href")
print(link1)
driver.get(link1)
driver.get("https://statisticstimes.com/economy/india/indian-states-gdp.php")


ranklist=[]
statelist=[]
gsdplist1=[]
gsdplist2=[]
sharelist=[]
gdplist=[]
#getting rank
rank=driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]")
for i in rank:
    #print(i.text)
    ranklist.append(i.text)

#getting state
state=driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]")
for i in state:
    #print(i.text)
    statelist.append(i.text)
statelist

#getting GSDP[19-20]
gsdp1=driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]")
for i in gsdp1:
    #print(i.text)
    gsdplist1.append(i.text)
gsdplist1

#getting GSDP[18-19]
gsdp2=driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]")
for i in gsdp2:
    #print(i.text)
    gsdplist2.append(i.text)
gsdplist2

#getting share
shares=driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]")
for i in shares:
    #print(i.text)
    sharelist.append(i.text)
sharelist

#getting GDP
gdps=driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]")
for i in gdps:
    #print(i.text)
    gdplist.append(i.text)
#gdplist
statistics=pd.DataFrame({})
statistics['Rank']=ranklist
statistics['State']=statelist
statistics['GSDP[19-20]']=gsdplist1
statistics['GSDP[18-19]']=gsdplist2
statistics['Share']=sharelist
statistics['GDP($billion)']=gdplist
statistics

Legality Response number from our URL is: <Response [200]>
https://statisticstimes.com/economy/india-statistics.php

,Rank,State,GSDP[19-20],GSDP[18-19],Share,GDP($billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"28,391","25,141",0.15%,"17,060"
62,30,Nagaland,-,"24,534",0.15%,-
63,31,Arunachal Pradesh,-,"22,488",0.13%,-
64,32,Mizoram,"24,424","20,947",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

In [6]:
url = "https://github.com/trending"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver=webdriver.Edge(r"C:/Users/DELL/Downloads/edgedriver_win64/msedgedriver.exe")
driver.get(url)
driver.maximize_window()
# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls
repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))


    
#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')

    

for i in repo_urls:
    driver.get(i)
    l=[]
    
    #scraping repositories discription
    try:
        repo = driver.find_element_by_xpath("/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[1]/div/p")
        repo_desc.append(repo.text)
    except NoSuchElementException:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    
    
     #scraping languages used   
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

Legality Response number from our URL is: <Response [200]>

,Title,Description,Contributors_count,Language_used
0,v4d1 / SpoofThatMail,Bash script to check if a domain or list of do...,2,[Shell]
1,windowjs / windowjs,Window.js is an open-source Javascript runtime...,No details available,"[C++, JavaScript, CMake, Python, Batchfile, Po..."
2,withastro / astro,"Build fast websites, faster. 🚀🧑‍🚀✨",216,"[TypeScript, JavaScript]"
3,CyC2018 / CS-Notes,📚 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计,231,[Java]
4,apache / superset,Apache Superset is a Data Visualization and Da...,711,"[TypeScript, Python, JavaScript, Jupyter Noteb..."
5,eugeneyan / applied-ml,📚 Papers & tech blogs by companies sharing the...,34,[No languages used]
6,cyrildiagne / ar-cutpaste,Cut and paste your surroundings using AR,6,"[TypeScript, Python, JavaScript]"
7,abigsoft / jdog202201,京东2022炸年兽,2,[C#]
8,sottlmarek / DevSecOps,Ultimate DevSecOps library,13,[No languages used]
9,facebookresearch / ConvNeXt,Code release for ConvNeXt model,3,[Python]
10,input-output-hk / plutus-apps,The Plutus application platform,110,"[Haskell, PureScript, Nix, SCSS, JavaScript, S..."
11,crater-invoice / crater,Open Source Invoicing Solution for Individuals...,66,"[PHP, Vue, JavaScript, Blade, Dockerfile, Shell]"
12,MoienTajik / AspNetCore-Developer-Roadmap,Roadmap to becoming an ASP.NET Core developer ...,20,[No languages used]
13,windowtoolbox / powershell-windows-toolbox,-,No details available,[No languages used]
14,commit-live-students / Data_Science_Masters_Pr...,-,No details available,"[Jupyter Notebook, HTML]"
15,itcharge / LeetCode-Py,⛽️「算法通关手册」，超详细的「算法与数据结构」基础讲解教程，「LeetCode」650+ ...,2,"[Python, Shell]"
16,ethereumbook / ethereumbook,"Mastering Ethereum, by Andreas M. Antonopoulos...",232,"[JavaScript, Vue, Solidity, HTML, Jupyter Note..."
17,synercys / annotated_latex_equations,"Examples of how to create colorful, annotated ...",3,"[TeX, Makefile]"
18,google / leveldb,LevelDB is a fast key-value storage library wr...,57,"[C++, C, CMake]"
19,ultralytics / yolov5,YOLOv5 🚀 in PyTorch > ONNX > CoreML > TFLite,203,[Python]
20,input-output-hk / plutus-pioneer-program,-,12,[Haskell]
21,files-community / Files,A modern file manager that pushes the boundari...,166,"[C#, C++]"
22,alyssaxuu / omni,The all-in-one tool to supercharge your produc...,4,"[JavaScript, CSS, HTML]"
23,QSCTech / zju-icicles,浙江大学课程攻略共享计划,86,"[HTML, C, C++, Verilog, Assembly, Python]"
24,prabhatsharma / zinc,Zinc Search engine. A lightweight alternative ...,10,"[Vue, Go, JavaScript, Dockerfile, Shell, Smarty]"

In [32]:
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://www.billboard.com/')
driver.maximize_window()

#getting the billboard 200 page
billboard_200=driver.find_element_by_xpath("//a[@class='c-link  lrv-a-unstyle-link lrv-u-whitespace-nowrap lrv-u-text-align-center lrv-u-display-table u-letter-spacing-0080 u-align-items-baseline lrv-u-color-grey-dark a-font-primary-bold u-font-size-11 lrv-u-color-black a-icon-magazine lrv-a-icon-after a-icon-after-11 lrv-u-padding-tb-050 lrv-u-padding-lr-1 lrv-u-text-transform-uppercase u-min-width-40p@desktop-max lrv-u-margin-lr-auto']")
driver.get(billboard_200.get_attribute('href'))

#creating the empty list
song=[]
name=[]
lweek=[]
peak=[]
week=[]
songlist=[]
#scraping for song name
for i in driver.find_elements_by_xpath("//h3[@id='title-of-a-story']"):
    song.append(i.text)
songlist=song[4::2]
print(songlist)
#scraping for name of the artist
x=driver.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']").text

for i in driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-padding-l-050 lrv-u-padding-l-1@mobile-max']/span[1]"):
    name.append(i.text)
name[:0]=[x]
print(name)
#scraping for last week rank 
for i in driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max lrv-u-flex-grow-1']/span[1]"):
    lweek.append(i.text)
print(lweek)
#scraping for peak rank
for i in driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-flex-grow-1']/span[1]"):
    peak.append(i.text)
print(peak)
#scraping for Weeks on board
for i in driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max lrv-u-flex-grow-1']/span[1]"):
    week.append(i.text)
print(week)
#creating the dataframe
print(len(songlist),len(name),len(lweek),len(peak),len(week))
'''Billboard100={'Song Name':song,'Artist Name':name,'Last Week Rank':lweek,'Peak Rank':peak,'Weeks on board':week}
Billboard100=pd.DataFrame(data=Billboard100)
Billboard100[:100]'''

['Encanto', '30', 'Dangerous: The Double Album', 'Sour', "Red (Taylor's Version)", 'Certified Lover Boy', 'Planet Her', 'The Highlights', 'Fighting Demons', 'Hall Of Fame', '=', 'Still Over It', 'F*ck Love', 'Happier Than Ever', 'Rumours', 'Montero', 'Live Life Fast', 'Future Nostalgia', 'My Turn', 'Shoot For The Stars Aim For The Moon', "Hollywood's Bleeding", 'An Evening With Silk Sonic', 'Goodbye & Good Riddance', 'What You See Is What You Get', 'SoulFly', 'Donda', 'From The Bayou', 'Justice', 'Legends Never Die', 'good kid, m.A.A.d city', "A Gangsta's Pain", 'Folklore', 'Sincerely, Kentrell', 'Fine Line', 'Evermore', 'Who Is Nardo Wick?', 'Greatest Hits', 'Sniper Gang Presents Syko Bob & SnapKatt: Nightmare Babies', 'Anniversary Trilogy', 'Whole Lotta Red', "This One's For You", 'Curtain Call: The Hits', 'If I Know Me', 'Diamonds', 'When We All Fall Asleep, Where Do We Go?', 'Dreamland', 'Hamilton: An American Musical', 'The Voice Of The Heroes', 'Starting Over', 'Traveller', 'Ctrl', 'Death Race For Love', 'The Melodic Blue', 'Abbey Road', 'YHLQMDLG', 'Lover', 'Positions', 'Chronicle The 20 Greatest Hits', 'ASTROWORLD', 'Nevermind', 'Sing 2', 'Luv Is Rage 2', 'El Ultimo Tour del Mundo', 'beerbongs & bentleys', 'DAMN.', 'Hot Pink', 'Universe: The 3rd Album, Neo Culture Technology (2021)', 'The GOAT', 'Let It Be (Soundtrack)', "Fearless (Taylor's Version)", '1989', '25', 'Eternal Atake', '2014 Forest Hills Drive', '?', 'Scorpion', '÷ (Divide)', 'Over It', 'Take Care', 'Legend: The Best Of...', '21', 'Las Leyendas Nunca Mueren', "Journey's Greatest Hits", 'Bigger Than Life Or Death', 'Pray 4 Love', 'AM', 'The Lockdown Sessions', 'The Off-Season', 'Greatest Hits', 'Greatest Hits', 'Die Lit', 'Doo-Wops & Hooligans', 'Metallica', 'Greatest Hits', 'Tickets To My Downfall', 'Stoney', 'reputation', 'Shiesty Season', 'Views', 'Arcane League Of Legends', 'Believers Never Die: Greatest Hits', 'Thats What They All Say', "When It's All Said And Done... Take Time", 'Man On The Moon: The End Of Day', 'Dont Smile At Me', 'The Voice', 'Gold: Greatest Hits', 'The Essential Michael Jackson', 'Graduation', 'Divinely Uninspired To A Hellish Extent', 'B4 AVA', 'Invasion Of Privacy', 'Macon', 'Circles', 'Man On The Moon III: The Chosen', 'Still Sleep?', 'Expensive Pain', 'Something For Thee Hotties: From Thee Archives', 'Top', 'MAP OF THE SOUL : 7', 'Magic', 'Inside (The Songs)', 'Back In Black', 'Moana', 'IGOR', 'Country Stuff (EP)', 'Blurryface', 'Purgatory', 'Born To Die', 'Blonde', 'Thank U, Next', 'American Teen', 'Free Dem Boyz', 'Vice Versa', 'Swimming', 'Human: The Double Album', 'Goldmine', 'Greatest Hits', 'T R A P S O U L', 'Greatest Hits', 'Trip At Knight', 'I Will Always Love You: The Best Of Whitney Houston', 'Ghetto Gospel', 'Good News', 'Thriller', 'Teenage Dream', 'Greatest Hits', 'Formula Of Love: O+T=<3', 'Sticker: The 3rd Album', 'Ready To Die', 'More Life', 'Nothing Was The Same', 'The College Dropout', 'Evolve', 'Speak Now', 'Music To Be Murdered By', 'All Time Greatest Hits', 'Please Excuse Me For Being Antisocial', 'Sounds Of Summer: The Very Best Of The Beach Boys', "Just Cause Y'all Waited 2", 'ANTI', 'Call Me If You Get Lost', 'Cry Baby', 'Destined 2 Win', 'Punk', 'Rich Slave', '9', '17', 'The Dark Side Of The Moon', 'La 167', 'DS2', 'Greatest Hits', '1', 'Wunna', 'Strait Out Of The Box', 'Currents', 'Flower Boy', 'Hotel California', 'My Beautiful Dark Twisted Fantasy', 'Frozen', 'Back Of My Mind', 'Greatest Hits: The Ultimate Collection', 'Khaled Khaled', 'X 100PRE', 'Purple Rain (Soundtrack)', 'In The Lonely Hour', 'Cuz I Love You', 'Frozen II', 'Birds In The Trap Sing McKnight', 'Hot Rocks 1964-1971', 'The Essential Billy Joel', 'Chilombo', "Devil's Got A New Disguise: The Very Best Of Aerosmith", 'Manic', 'High Off Life', 'Nothing But The Best', 'The Very Best Of Daryl Hall John Oates', 'Harry Styles', 'Hey World', 'Meet The Woo, V.2', "Bob Saget, Comedian and 'Full House' Star, Dies at 65", "The Ace Family's Foreclosed Mansion Finally Hits the Market", 'HBO Max, Amazon and Sky Shows to Light Up Berlin Fest’s TV Lineup', 'Consumers Take to Online Marketplaces, Survey Says', '', '', 'Have a Tip?']

AttributeError: 'list' object has no attribute 'text'

In [43]:
driver=webdriver.Chrome(r"chromedriver.exe")
 
driver.get("https://www.naukri.com/recruiters")
#getting recuriter link

search=driver.find_element_by_xpath("//div[@class='inpWrap']/input")
search.send_keys("Data science")
search=driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']")
search.click()

name = []
designation = []
company = []
skills = []
location = []

# fetching Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    name.append(i.text)
    
# fetching Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    designation.append(i.text)

# fetching Company names
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    company.append(i.text)
    
# fetching  Skills
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        skills.append(i.text)
    except NoSuchElementException:
        skills.append('-')
                
# fetching Locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    location.append(i.text)
    
# Creating a dataframe
data = list(zip(name, designation, company, skills, location))
df = pd.DataFrame(data, columns = ["Name", "Designation", "Company Name", "Skills they hire for", "Location"])
df

,Name,Designation,Company Name,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Anik Agrawal
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Company Recruiter
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Ahmedabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",subhas patel
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Founder CEO
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",UK - (london)
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Recruitment Lead Consultant
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Vadodara / Baroda
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Balu Ramesh
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",HR Administrator
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Trivandrum
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Asif Lucknowi
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Director
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Indore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",InstaFinancials
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Human Resource
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
30,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Priyanka Akiri
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",HR Manager
32,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Hyderabad
33,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Kalpana Dumpala
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Executive Hiring
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Hyderabad / Secunderabad
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Mubarak
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Company HR
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Kushal Rastogi
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Company HR
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Mumbai
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Mahesh Babu Channa
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",HR Team Lead
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Sakshi Chhikara
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Assistant Manager HR
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Chandigarh
48,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Kapil Devang
49,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",HR Manager

In [44]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

Book_name = []
Author_name = []
Volume_sold = []
Publisher = []
Genre = []

try: # Scraping Book name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[2]"):
        Book_name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Author name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[3]"):
        Author_name.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Volume sold
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[4]"):
        Volume_sold.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Publisher
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[5]"):
        Publisher.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[6]"):
        Genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
# Creating data frame 
Books=pd.DataFrame({'Book Name': Book_name, 'Author Name': Author_name, 'Volume Sold': Volume_sold,
                    'Publisher': Publisher, 'Genre' : Genre})
Books

Legality Response number from our URL is: <Response [200]>

,Book Name,Author Name,Volume Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [45]:
url = "https://www.imdb.com/list/ls095964455/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

name = []
year = []
genre = []
runtime = []
rating = []
vote = []

try: # Scraping Name
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
        name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Year span
    for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
        year.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[5]"):
        genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Run time
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[3]"):
        runtime.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Ratings
    for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]"):
        rating.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping votes
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]"):
        vote.append(i.text)
except NoSuchElementException as e:
    print("-")

# Creating a dataframe 
imdb=pd.DataFrame({'Name':name, 'Year Span':year, 'Genre':genre, 'Run Time':runtime, 'Ratings':rating, 'Votes':vote})
imdb

Legality Response number from our URL is: <Response [200]>

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,930,939"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"951,686"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"922,293"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"276,353"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"236,598"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"47,189"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,981"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"183,064"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"38,348"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"218,059"

In [46]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(1)


#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping data type
data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset names
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021